//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basic_User()
        {
            this.Basic_Celebrity = new HashSet<Basic_Celebrity>();
            this.Basic_Collection = new HashSet<Basic_Collection>();
            this.Basic_Comment = new HashSet<Basic_Comment>();
            this.Basic_Movie = new HashSet<Basic_Movie>();
            this.Basic_Operation_Log = new HashSet<Basic_Operation_Log>();
            this.Basic_Request = new HashSet<Basic_Request>();
            this.Basic_Resource = new HashSet<Basic_Resource>();
            this.Basic_Movie_Visit = new HashSet<Basic_Movie_Visit>();
            this.Basic_User_Signin = new HashSet<Basic_User_Signin>();
        }
    
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Avatar { get; set; }
        public string Cover { get; set; }
        public Nullable<bool> Limit { get; set; }
        public Nullable<System.DateTime> Create_Time { get; set; }
        public Nullable<System.DateTime> Alter_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Celebrity> Basic_Celebrity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Collection> Basic_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Comment> Basic_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Movie> Basic_Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Operation_Log> Basic_Operation_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Request> Basic_Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Resource> Basic_Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_Movie_Visit> Basic_Movie_Visit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basic_User_Signin> Basic_User_Signin { get; set; }
    }
}
