//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basic_Operation_Log
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Target { get; set; }
        public Nullable<System.Guid> User { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Note { get; set; }
    
        public virtual Basic_User Basic_User { get; set; }
    }
}
