//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class MovieResShareEntities : DbContext
    {
        public MovieResShareEntities()
            : base("name=MovieResShareEntities")
        {
            var ensureDLLIsCopied =
                    System.Data.Entity.SqlServer.SqlProviderServices.Instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Basic_Celebrity> Basic_Celebrity { get; set; }
        public virtual DbSet<Basic_Collection> Basic_Collection { get; set; }
        public virtual DbSet<Basic_Comment> Basic_Comment { get; set; }
        public virtual DbSet<Basic_Movie> Basic_Movie { get; set; }
        public virtual DbSet<Basic_Operation_Log> Basic_Operation_Log { get; set; }
        public virtual DbSet<Basic_Recommend> Basic_Recommend { get; set; }
        public virtual DbSet<Basic_Request> Basic_Request { get; set; }
        public virtual DbSet<Basic_Resource> Basic_Resource { get; set; }
        public virtual DbSet<Basic_User> Basic_User { get; set; }
        public virtual DbSet<Step_Celeb_Avatar> Step_Celeb_Avatar { get; set; }
        public virtual DbSet<Step_Celeb_Work> Step_Celeb_Work { get; set; }
        public virtual DbSet<Step_Movie_Country> Step_Movie_Country { get; set; }
        public virtual DbSet<Step_Movie_Genre> Step_Movie_Genre { get; set; }
        public virtual DbSet<Step_Movie_Lang> Step_Movie_Lang { get; set; }
        public virtual DbSet<Step_Movie_Poster> Step_Movie_Poster { get; set; }
        public virtual DbSet<Step_Movie_Rating> Step_Movie_Rating { get; set; }
        public virtual DbSet<Basic_Movie_Visit> Basic_Movie_Visit { get; set; }
        public virtual DbSet<Basic_User_Signin> Basic_User_Signin { get; set; }
    }
}
