//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRDataEntities : DbContext
    {
        public MRDataEntities()
            : base("name=MRDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Album> tbl_Album { get; set; }
        public virtual DbSet<tbl_Ask> tbl_Ask { get; set; }
        public virtual DbSet<tbl_Celebrity> tbl_Celebrity { get; set; }
        public virtual DbSet<tbl_Comment> tbl_Comment { get; set; }
        public virtual DbSet<tbl_Country> tbl_Country { get; set; }
        public virtual DbSet<tbl_Discovery> tbl_Discovery { get; set; }
        public virtual DbSet<tbl_FavorRes> tbl_FavorRes { get; set; }
        public virtual DbSet<tbl_FollowAlbum> tbl_FollowAlbum { get; set; }
        public virtual DbSet<tbl_GenreMovie> tbl_GenreMovie { get; set; }
        public virtual DbSet<tbl_Language> tbl_Language { get; set; }
        public virtual DbSet<tbl_Mark> tbl_Mark { get; set; }
        public virtual DbSet<tbl_MarkCeleb> tbl_MarkCeleb { get; set; }
        public virtual DbSet<tbl_MarkMovie> tbl_MarkMovie { get; set; }
        public virtual DbSet<tbl_Movie> tbl_Movie { get; set; }
        public virtual DbSet<tbl_Notice> tbl_Notice { get; set; }
        public virtual DbSet<tbl_Resource> tbl_Resource { get; set; }
        public virtual DbSet<tbl_UserAccount> tbl_UserAccount { get; set; }
        public virtual DbSet<tbl_WithAsk> tbl_WithAsk { get; set; }
        public virtual DbSet<tbl_Work> tbl_Work { get; set; }
    }
}
