//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ask()
        {
            this.tbl_WithAsk = new HashSet<tbl_WithAsk>();
        }
    
        public string ask_Id { get; set; }
        public string ask_User { get; set; }
        public string ask_Movie { get; set; }
        public Nullable<System.DateTime> ask_Time { get; set; }
        public Nullable<int> ask_With { get; set; }
        public string ask_Note { get; set; }
        public Nullable<bool> ask_State { get; set; }
    
        public virtual tbl_Movie tbl_Movie { get; set; }
        public virtual tbl_UserAccount tbl_UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WithAsk> tbl_WithAsk { get; set; }
    }
}
