//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UserAccount()
        {
            this.tbl_Album = new HashSet<tbl_Album>();
            this.tbl_Ask = new HashSet<tbl_Ask>();
            this.tbl_Celebrity = new HashSet<tbl_Celebrity>();
            this.tbl_Comment = new HashSet<tbl_Comment>();
            this.tbl_FavorRes = new HashSet<tbl_FavorRes>();
            this.tbl_FollowAlbum = new HashSet<tbl_FollowAlbum>();
            this.tbl_Mark = new HashSet<tbl_Mark>();
            this.tbl_MarkCeleb = new HashSet<tbl_MarkCeleb>();
            this.tbl_MarkMovie = new HashSet<tbl_MarkMovie>();
            this.tbl_Movie = new HashSet<tbl_Movie>();
            this.tbl_Notice = new HashSet<tbl_Notice>();
            this.tbl_Resource = new HashSet<tbl_Resource>();
            this.tbl_WithAsk = new HashSet<tbl_WithAsk>();
        }
    
        public string user_Id { get; set; }
        public string user_Account { get; set; }
        public string user_Password { get; set; }
        public string user_EmailAddress { get; set; }
        public string user_Avatar { get; set; }
        public string user_Cover { get; set; }
        public Nullable<System.DateTime> user_CreateTime { get; set; }
        public Nullable<System.DateTime> user_AlterTime { get; set; }
        public Nullable<bool> user_IsAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Album> tbl_Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Ask> tbl_Ask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Celebrity> tbl_Celebrity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Comment> tbl_Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FavorRes> tbl_FavorRes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FollowAlbum> tbl_FollowAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Mark> tbl_Mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MarkCeleb> tbl_MarkCeleb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MarkMovie> tbl_MarkMovie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Movie> tbl_Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Notice> tbl_Notice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Resource> tbl_Resource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WithAsk> tbl_WithAsk { get; set; }
    }
}
