//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Resource()
        {
            this.tbl_FavorRes = new HashSet<tbl_FavorRes>();
            this.tbl_Notice = new HashSet<tbl_Notice>();
        }
    
        public string res_Id { get; set; }
        public string res_Name { get; set; }
        public string res_Content { get; set; }
        public Nullable<float> res_Size { get; set; }
        public string res_User { get; set; }
        public string res_Movie { get; set; }
        public Nullable<System.DateTime> res_Time { get; set; }
        public Nullable<int> res_FavorCount { get; set; }
        public Nullable<byte> res_Type { get; set; }
        public Nullable<byte> res_Status { get; set; }
        public string res_Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FavorRes> tbl_FavorRes { get; set; }
        public virtual tbl_Movie tbl_Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Notice> tbl_Notice { get; set; }
        public virtual tbl_UserAccount tbl_UserAccount { get; set; }
    }
}
