//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Mark
    {
        public string mark_Id { get; set; }
        public byte mark_Type { get; set; }
        public string mark_User { get; set; }
        public string mark_Target { get; set; }
        public Nullable<System.DateTime> mark_Time { get; set; }
    
        public virtual tbl_UserAccount tbl_UserAccount { get; set; }
    }
}
