//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Album()
        {
            this.tbl_FollowAlbum = new HashSet<tbl_FollowAlbum>();
        }
    
        public string album_Id { get; set; }
        public string album_Title { get; set; }
        public string album_User { get; set; }
        public string album_Item { get; set; }
        public string album_Summary { get; set; }
        public Nullable<System.DateTime> album_Time { get; set; }
        public Nullable<System.DateTime> album_AlterTime { get; set; }
        public string album_Cover { get; set; }
        public Nullable<int> album_Visit { get; set; }
    
        public virtual tbl_UserAccount tbl_UserAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_FollowAlbum> tbl_FollowAlbum { get; set; }
    }
}
