//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieResources
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FollowAlbum
    {
        public string follow_Id { get; set; }
        public string follow_User { get; set; }
        public string follow_Album { get; set; }
        public Nullable<System.DateTime> follow_Time { get; set; }
    
        public virtual tbl_Album tbl_Album { get; set; }
        public virtual tbl_UserAccount tbl_UserAccount { get; set; }
    }
}
